// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDky2OReIXaM6gqd587zT1haXAaXumG-l0',
    appId: '1:86231630171:web:8da9b22a012779e13a9a7e',
    messagingSenderId: '86231630171',
    projectId: 'diseno-apps-moviles-ailton-37',
    authDomain: 'diseno-apps-moviles-ailton-37.firebaseapp.com',
    storageBucket: 'diseno-apps-moviles-ailton-37.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKTePgVXGNtAeJj9HZh4hgkP9bUlsJCWs',
    appId: '1:86231630171:android:40beb757e3c825b93a9a7e',
    messagingSenderId: '86231630171',
    projectId: 'diseno-apps-moviles-ailton-37',
    storageBucket: 'diseno-apps-moviles-ailton-37.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATNiG7oqKIlW0ZviuZqzX-7jJOxc1o4VU',
    appId: '1:86231630171:ios:85eb0c88d9b1b51b3a9a7e',
    messagingSenderId: '86231630171',
    projectId: 'diseno-apps-moviles-ailton-37',
    storageBucket: 'diseno-apps-moviles-ailton-37.firebasestorage.app',
    iosBundleId: 'com.example.helloWorld',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATNiG7oqKIlW0ZviuZqzX-7jJOxc1o4VU',
    appId: '1:86231630171:ios:85eb0c88d9b1b51b3a9a7e',
    messagingSenderId: '86231630171',
    projectId: 'diseno-apps-moviles-ailton-37',
    storageBucket: 'diseno-apps-moviles-ailton-37.firebasestorage.app',
    iosBundleId: 'com.example.helloWorld',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDky2OReIXaM6gqd587zT1haXAaXumG-l0',
    appId: '1:86231630171:web:ecf13222501756b03a9a7e',
    messagingSenderId: '86231630171',
    projectId: 'diseno-apps-moviles-ailton-37',
    authDomain: 'diseno-apps-moviles-ailton-37.firebaseapp.com',
    storageBucket: 'diseno-apps-moviles-ailton-37.firebasestorage.app',
  );
}
